version: "3"

services:
  mfem-cpu:
    build:
      context: mfem-cpu
      args:
        num_jobs: 8
        hypre_version: 2.31.0
        uid: 10000
        gid: 10000
    image: mfem-cpu:latest

  mfem-cuda:
    build:
      context: mfem-cuda
      args:
        num_jobs: 8
        cuda_arch_sm: 75
        hypre_version: 2.31.0
        uid: 10000
        gid: 10000
    image: mfem-cuda:latest

  fenics:
    build:
      context: fenics
      args:
        uid: 10000
        gid: 10000
    image: fenics:latest

  fenics-mfem-cpu:
    build:
      context: fenics-mfem-cpu
      args:
        num_jobs: 8
        hypre_version: 2.31.0
        uid: 10000
        gid: 10000
    image: fenics-mfem-cpu:latest
